#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &

bspc monitor primary -d 1 2 3 4 5 6 7 8 9 10

#bspc config border_width         2
bspc config window_gap 15 &

bspc config split_ratio 0.52 &
bspc config borderless_monocle true &
bspc config single_monocle = true &
bspc config gapless_monocle true &
bspc config pointer_motion_interval 5 &
bspc config border_width 0 &

xsetroot -cursor_name left_ptr &

dunst -config $HOME/.config/bspwm/dunstrc &

#picom --config $HOME/.config/bspwm/picom_configuration/1.conf &
picom --config $HOME/.config/picom/picom.conf &

#	Autosrart
#sxhkd &
nitrogen --restore &
#dunst &
polybar &

feh --bg-scale ~/Pictures/012.png &

/usr/bin/pipewire &
/usr/bin/pipewire-pulse &
/usr/bin/pipewire-media-session &

#~/.config/polybar/launch.sh &

#polybar Main &
#polybar workspaces &
#polybar cpu &
#polybar date &
#polybar filesystem&
#polybar memory &
#polybar now-playing &
#polybar volume &

systemctl start bluetooth.service &
flameshot &
